name: pymc_playground
channels:
  - conda-forge
dependencies:
  - arviz
  - black
  - jupyter
  - jupyterlab
  - jupyter_nbextensions_configurator
  - jupytext
  - libblas=*=*mkl
  - matplotlib
  - mkl-service
  - nbqa
  - numpy
  - pandas
  - pip
  - pymc
  - python-graphviz
  - rise
  - seaborn
  - pyyaml=5.4.1
